export interface FakturowniaInvoicePositionAdditionalFields {
  gtu_codes: string[];
}

export interface FakturowniaInvoicePosition {
  id: number;
  invoice_id: number;
  name: string;
  description?: string | null;
  price_net: string;
  quantity: string;
  total_price_gross: string;
  total_price_net: string;
  account_id: number;
  created_at: Date;
  updated_at: Date;
  additional_info_desc: string | null;
  additional_info: boolean;
  quantity_unit?: null | string;
  tax: string;
  price_gross: string;
  price_tax: string;
  total_price_tax: string;
  kind?: null | string;
  invoice_position_id?: null | string;
  product_id: number;
  deleted: boolean;
  discount?: null | string;
  discount_percent?: null | string;
  tax2: string;
  exchange_rate: string;
  accounting_tax_kind?: null | string;
  code?: null | string;
  additional_fields: FakturowniaInvoicePositionAdditionalFields;
}

export interface FakturowniaInvoice {
  id: number | string;
  user_id: number;
  app: string | null;
  number: string;
  place?: string | null;
  sell_date: string;
  payment_type: string;
  price_net: string;
  price_gross: string;
  currency: string;
  status: string;
  description?: string | null;
  seller_name: string;
  seller_tax_no: string;
  seller_street: string;
  seller_post_code: string;
  seller_city: string;
  seller_country: string;
  seller_email: string;
  seller_phone: string;
  seller_fax: string;
  seller_www: string;
  seller_person: string;
  seller_bank: string;
  seller_bank_account: string;
  buyer_name: string;
  buyer_tax_no: string;
  buyer_post_code?: string | null;
  buyer_city?: string | null;
  buyer_street?: string | null;
  buyer_first_name?: string | null;
  buyer_country?: string | null;
  created_at: Date;
  updated_at: Date;
  token: string;
  buyer_email: string;
  buyer_www?: string | null;
  buyer_fax?: string | null;
  buyer_phone?: string | null;
  kind: string;
  pattern: string;
  pattern_nr?: string | null;
  pattern_nr_m: number;
  pattern_nr_d?: string | null;
  client_id: number;
  payment_to: string;
  paid: string;
  seller_bank_account_id?: string | null;
  lang: string;
  issue_date: string;
  price_tax: string;
  department_id: number;
  correction?: string | null;
  buyer_note?: string | null;
  additional_info_desc?: string | null;
  additional_info: boolean;
  product_cache: string;
  buyer_last_name?: any;
  from_invoice_id?: any;
  oid?: any;
  discount: string;
  show_discount: boolean;
  sent_time?: any;
  print_time?: any;
  recurring_id?: any;
  tax2_visible?: any;
  warehouse_id?: any;
  paid_date: string;
  product_id?: any;
  issue_year: number;
  internal_note?: any;
  invoice_id?: any;
  invoice_template_id: number;
  description_long?: any;
  buyer_tax_no_kind?: any;
  seller_tax_no_kind?: any;
  description_footer?: any;
  sell_date_kind?: any;
  payment_to_kind: string;
  exchange_currency?: any;
  discount_kind: string;
  income: boolean;
  from_api: boolean;
  category_id?: any;
  warehouse_document_id?: any;
  exchange_kind: string;
  exchange_rate: string;
  use_delivery_address: boolean;
  delivery_address?: any;
  accounting_kind?: any;
  buyer_person: string;
  buyer_bank_account?: any;
  buyer_bank?: any;
  buyer_mass_payment_code?: any;
  exchange_note: string;
  buyer_company: boolean;
  show_attachments: boolean;
  exchange_currency_rate?: any;
  has_attachments: boolean;
  exchange_date?: any;
  attachments_count: number;
  delivery_date: string;
  fiscal_status?: any;
  use_moss: boolean;
  transaction_date: string;
  email_status?: any;
  exclude_from_stock_level: boolean;
  exclude_from_accounting: boolean;
  exchange_rate_den: string;
  exchange_currency_rate_den: string;
  accounting_scheme?: any;
  exchange_difference: string;
  not_cost: boolean;
  reverse_charge: boolean;
  issuer?: any;
  use_issuer: boolean;
  cancelled: boolean;
  recipient_id?: any;
  recipient_name?: any;
  test: boolean;
  discount_net?: any;
  approval_status?: any;
  accounting_vat_tax_date: string;
  accounting_income_tax_date: string;
  accounting_other_tax_date?: any;
  accounting_status?: any;
  normalized_number?: any;
  na_tax_kind?: any;
  issued_to_receipt: boolean;
  payment_url?: any;
  view_url: string;
  gtu_codes: any[];
  procedure_designations: any[];
  positions: FakturowniaInvoicePosition[];
}
